"$schema" = "schemas/schema.json"

[default]
description = "Default permissions for the ios-bookmark plugin."
permissions = [
  "allow-pick-file-bookmark",
  "allow-read-file-bookmark",
  "allow-read-file-bookmark-data",
  "allow-write-file-bookmark",
  "allow-write-file-bookmark-data",
  "allow-pick-folder-bookmark",
  "allow-list-folder-bookmark",
  "allow-read-folder-bookmark",
  "allow-read-folder-bookmark-data",
  "allow-write-folder-bookmark",
  "allow-write-folder-bookmark-data",
  "allow-create-dir",
  "allow-create-file",
  "allow-rename",
  "allow-move",
  "allow-remove",
  "allow-check-bookmark",
  "allow-release-bookmark",
]
